language: php

php:
  - 5.4
  - 5.5

before_script:
    - composer self-update
    - composer install --dev --no-interaction --prefer-source

script:
    # - ./bin/behat  --no-snippets --no-paths --verbose
    - ./bin/phpspec run -fpretty --verbose
