peterjmit_blog_new:
    pattern:   /new
    defaults:  { _controller: peterjmit_blog.post_controller:newAction }

peterjmit_blog_create:
    pattern:   /create
    defaults:  { _controller: peterjmit_blog.post_controller:createAction }
    methods: [POST]

peterjmit_post_publish:
    pattern: /publish/{id}
    defaults:  { _controller: peterjmit_blog.post_controller:publishAction }
    methods: [POST]
