_blog_bundle_security:
    resource: "@PeterjmitBlogBundle/Resources/config/routing/security.yml"
    prefix:   /

_blog_bundle_reading:
    resource: "@PeterjmitBlogBundle/Resources/config/routing/reading.yml"
