parameters:
    peterjmit_blog.post_entity.class: Peterjmit\BlogBundle\Entity\Post
    peterjmit_blog.post_repository.class: Peterjmit\BlogBundle\Doctrine\PostRepository
    peterjmit_blog.paged_post_repository.class: Peterjmit\BlogBundle\Doctrine\PagedPostRepository
    peterjmit_blog.blog_controller.class: Peterjmit\BlogBundle\Controller\BlogController
    peterjmit.form.type.post.class: Peterjmit\BlogBundle\Form\Type\PostType
    peterjmit_blog.post_controller.class: Peterjmit\BlogBundle\Controller\PostController
    peterjmit_blog.post_manager.class: Peterjmit\BlogBundle\Doctrine\PostManager
    peterjmit_blog.controller_utilities.class: Peterjmit\BlogBundle\Util\ControllerUtilities
    peterjmit_blog.twig.blog_configuration.class: Peterjmit\BlogBundle\Twig\Extension\BlogConfiguration

services:
    peterjmit_blog.post_repository:
        class: %peterjmit_blog.post_repository.class%
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: [%peterjmit_blog.post_entity.class%]

    peterjmit_blog.paged_post_repository:
        class: %peterjmit_blog.paged_post_repository.class%
        arguments: [@peterjmit_blog.post_repository, %peterjmit_blog.posts_per_page%]

    peterjmit_blog.post_manager:
        class: %peterjmit_blog.post_manager.class%
        arguments: [@doctrine.orm.entity_manager, @peterjmit_blog.post_repository, %peterjmit_blog.post_entity.class%]

    peterjmit_blog.controller_utilities:
        class: %peterjmit_blog.controller_utilities.class%
        arguments: [@router, @templating, @form.factory]

    peterjmit_blog.blog_controller:
        class: %peterjmit_blog.blog_controller.class%
        arguments: [@peterjmit_blog.paged_post_repository, @templating]

    peterjmit.form.type.post:
        class: %peterjmit.form.type.post.class%
        arguments: [%peterjmit_blog.post_entity.class%]
        tags:
            - { name: form.type, alias: peterjmit_post }

    peterjmit_blog.post_controller:
        class: %peterjmit_blog.post_controller.class%
        arguments: [@peterjmit_blog.post_manager, @peterjmit_blog.controller_utilities]

    peterjmit_blog.twig.blog_configuration:
        class: %peterjmit_blog.twig.blog_configuration.class%
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    pagerfanta.view.blog_view:
        class: Pagerfanta\View\OptionableView
        public: false
        arguments:
            - @pagerfanta.view.twitter_bootstrap3
            - { proximity: 2, prev_message: "&laquo;", next_message: "&raquo;" }
        tags:
            - { name: pagerfanta.view, alias: blog_view }
